#!/bin/bash
#
#	/etc/rc.d/init.d/barserver
#
#	BAR server start script
#	Copyright 2007-2016 Torsten Rupp
#

### BEGIN INIT INFO
# Provides:          barserver
# Required-Start:    $syslog $local_fs $network $remote_fs
# Required-Stop:     $syslog $local_fs $network $remote_fs
# Should-Start:      $time ypbind sendmail
# Should-Stop:       $time ypbind sendmail
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: BAR server daemon
# Description:       Backup ARchiver server for backup/restore
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# check for binaries
BAR_BIN=/usr/bin/bar
if test ! -x $BAR_BIN; then
  echo "$BAR_BIN not installed"
  exit 5
fi

# check for existence of needed config file
BAR_CONFIG=/etc/bar/bar.cfg
if test ! -r $BAR_CONFIG; then
  echo "$BAR_CONFIG cannot be read"
  exit 6
fi

start() {
	echo -n "Starting BAR server: "
	daemon $BAR_BIN --daemon --verbose=3
        RETVAL=$?
	touch /var/lock/subsys/barserver
	return $RETVAL
}

stop() {
	echo -n "Shutting down BAR server: "
	killproc $BAR_BIN TERM
        RETVAL=$?
	rm -f /var/lock/subsys/barserver
	return $RETVAL
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
        status $BAR_BIN
	;;
    restart)
    	stop
	start
	;;
    reload)
	;;
    condrestart)
	[ -f /var/lock/subsys/barserver ] && restart || :
        ;;
    probe)
	;;
    *)
	echo "Usage: barserver {start|stop|status|restart}"
	exit 1
	;;
esac
exit $?
