#! /bin/sh
#
#	/etc/rc.d/init.d/barserver
#
#	BAR server start script
#	Copyright 2007-2019 Torsten Rupp
#

### BEGIN INIT INFO
# Provides:          barserver
# Required-Start:    $syslog $local_fs $network $remote_fs
# Required-Stop:     $syslog $local_fs $network $remote_fs
# Should-Start:      $time ypbind sendmail
# Should-Stop:       $time ypbind sendmail
# Default-Start:     3 5
# Default-Stop:      0 1 2 4 6
# Short-Description: BAR server daemon
# Description:       Backup ARchiver server for backup/restore
### END INIT INFO

NAME=bar
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
CONFIGFILE=/etc/bar/bar.cfg
DAEMON_ARGS="-c $CONFIGFILE --daemon --pid-file=$PIDFILE --verbose=0 --quiet"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/barserver

# source LSB init functions
#. /lib/lsb/init-functions

# sourced shell functions
if test -f /etc/rc.status; then
  . /etc/rc.status
fi
if test -f /etc/init.d/functions; then
  . /etc/init.d/functions
fi

# check for binaries
if test ! -x $DAEMON; then
  echo "$DAEMON not installed"
  exit 5
fi

# check for config file
if test ! -r $CONFIGFILE; then
  echo "$CONFIGFILE cannot be read"
  exit 6
fi

case "$1" in
    start)
	echo -n "Starting BAR server "
	daemon $DAEMON $DAEMON_ARGS
	;;
    stop)
	echo -n "Shutting down BAR server "
	killproc -p $PIDFILE -TERM $DAEMON
	;;
    reload)
        failure
	;;
    restart)
	$0 stop
	$0 start
	;;
    status)
	echo -n "Checking for service BAR server: "
	if test ! -f $PIDFILE; then
          echo "stopped"
        elif test ! -d /proc/`cat $PIDFILE`; then
          echo "stopped"
        else
          echo "running"
        fi
	;;
    *)
	echo "Usage: $0 {start|stop|reload|restart|status}"
	exit 1
	;;
esac
