#!/bin/bash
#
#	/etc/rc.d/init.d/barserver
#
#	<description of the *service*>
#	<any general comments about this init script>
#
# <tags -- see below for tag definitions.  *Every line* from the top
#  of the file to the end of the tags section must begin with a #
#  character.  After the tags section, there should be a blank line.
#  This keeps normal comments in the rest of the file from being
#  mistaken for tags, should they happen to fit the pattern.>

# Source function library.
. /etc/init.d/functions

# check for binaries
BAR_BIN=/usr/bin/bar
if test ! -x $BAR_BIN; then
  echo "$BAR_BIN not installed"
  exit 5
fi

# check for existence of needed config file
BAR_CONFIG=/etc/bar/bar.cfg
if test ! -r $BAR_CONFIG; then
  echo "$BAR_CONFIG cannot be read"
  exit 6
fi

start() {
	echo -n "Starting BAR server: "
	daemon -20 $BAR_BIN --daemon --verbose=3
        RETVAL=$?
	touch /var/lock/subsys/barserver
	return $RETVAL
}	

stop() {
	echo -n "Shutting down BAR server: "
	killproc $BAR_BIN TERM
        RETVAL=$?
	rm -f /var/lock/subsys/barserver
	return $RETVAL
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	;;
    restart)
    	stop
	start
	;;
    reload)
	;;
    condrestart)
	[ -f /var/lock/subsys/barserver ] && restart || :
        ;;
    probe)
	;;
    *)
	echo "Usage: barserver {start|stop]"
	exit 1
	;;
esac
exit $?
