VERSION = 1.2
INSTALL_PATH = /usr/local

install: mclistbox.tcl pkgIndex.tcl
	install -d $(INSTALL_PATH)/lib/mclistbox$(VERSION)
	install mclistbox.tcl $(INSTALL_PATH)/lib/mclistbox$(VERSION)
	install pkgIndex.tcl $(INSTALL_PATH)/lib/mclistbox$(VERSION)
