#! /bin/sh
#
#	/etc/rc.d/init.d/barserver
#
#	BAR server start script
#	Copyright 2007-2025 Torsten Rupp
#

### BEGIN INIT INFO
# Provides:          barserver
# Required-Start:    $syslog $local_fs $network $remote_fs
# Required-Stop:     $syslog $local_fs $network $remote_fs
# Should-Start:      $time ypbind sendmail
# Should-Stop:       $time ypbind sendmail
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: BAR server daemon
# Description:       Start BAR server for backup/restore
### END INIT INFO

NAME=bar
BAR_BIN=/usr/bin/$NAME
BAR_CONFIG_FILENAME=/etc/bar/bar.cfg
BAR_PID_FILENAME=/run/$NAME.pid
BAR_ARGS="--config $BAR_CONFIG_FILENAME --daemon --pid-file=$BAR_PID_FILENAME --verbose=0 --quiet"
BAR_SCRIPT_FILENAME=/etc/init.d/barserver
DESCRIPTION="barserver"

# source LSB init functions
#. /lib/lsb/init-functions

# shell functions sourced from /etc/rc.status:
. /etc/rc.status

# check for binaries
if test ! -x $BAR_BIN; then
  echo "$BAR_BIN not installed"
  exit 5
fi

# check for configuration file
if test ! -r $BAR_CONFIG_FILENAME; then
  echo "$BAR_CONFIG_FILENAME cannot be read"
  exit 6
fi

case "$1" in
    start)
	echo -n "Starting BAR server "
	startproc $BAR_BIN --daemon --verbose=3
	rc_status -v
	;;
    stop)
	echo -n "Shutting down BAR server "
	killproc -TERM $BAR_BIN
	rc_status -v
	;;
    reload)
        rc_failed 3
	rc_status -v
	;;
    restart)
	$0 stop
	$0 start
	rc_status -v
	;;
    status)
	echo -n "Checking for service BAR server "
	checkproc $BAR_BIN
	rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop|reload|restart|status}"
	exit 1
	;;
esac
rc_exit
